//! Story Director — semantic world state and beat progression.
//!
//! The narrative layer is modelled as a graph of [`Beat`]s. Each beat is an
//! object; each allowed transition is a generating morphism; a playable session
//! is a path through the free category generated by that graph. A user choice
//! selects a different arrow without exploding the application state machine,
//! and branches may reconverge later.
//!
//! Crucially, narrative truth is stored as [`Facts`] — semantic world state —
//! **not** as countdown timers. `PlagueActive = true` stays true until something
//! explicitly clears it, so scene effects can attach to the fact rather than
//! being manually refreshed every frame.
//!
//! The director owns: the current beat, beat time, facts, mounted effect bundles,
//! an event queue and an optional [`StoryTrace`] for deterministic replay. It
//! does **not** own the terminal, `Context`, input polling, ANSI or layout — the
//! application converts keyboard input into semantic [`StoryEvent`]s and calls
//! [`StoryDirector::update`].

use crate::scene::{Effect, EffectBundle, Presentation, Scene};
use std::collections::BTreeMap;
use std::time::Duration;

// ---------------------------------------------------------------------------
// Facts
// ---------------------------------------------------------------------------

/// A typed fact value.
#[derive(Debug, Clone, PartialEq)]
pub enum FactValue {
    Bool(bool),
    Number(f32),
    Text(String),
}

impl FactValue {
    fn as_bool(&self) -> Option<bool> {
        match self {
            FactValue::Bool(b) => Some(*b),
            _ => None,
        }
    }
    fn as_number(&self) -> Option<f32> {
        match self {
            FactValue::Number(n) => Some(*n),
            _ => None,
        }
    }
    fn as_text(&self) -> Option<&str> {
        match self {
            FactValue::Text(s) => Some(s),
            _ => None,
        }
    }
}

/// Semantic world state keyed by name.
///
/// Absent booleans read as `false`, absent numbers as `0.0`, absent text as `""`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Facts {
    map: BTreeMap<String, FactValue>,
}

impl Facts {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn set_bool(&mut self, key: impl Into<String>, v: bool) {
        self.map.insert(key.into(), FactValue::Bool(v));
    }

    pub fn set_number(&mut self, key: impl Into<String>, v: f32) {
        self.map.insert(key.into(), FactValue::Number(v));
    }

    pub fn set_text(&mut self, key: impl Into<String>, v: impl Into<String>) {
        self.map.insert(key.into(), FactValue::Text(v.into()));
    }

    pub fn bool(&self, key: &str) -> bool {
        self.map
            .get(key)
            .and_then(FactValue::as_bool)
            .unwrap_or(false)
    }

    pub fn number(&self, key: &str) -> f32 {
        self.map
            .get(key)
            .and_then(FactValue::as_number)
            .unwrap_or(0.0)
    }

    pub fn text(&self, key: &str) -> &str {
        self.map.get(key).and_then(FactValue::as_text).unwrap_or("")
    }

    pub fn get(&self, key: &str) -> Option<&FactValue> {
        self.map.get(key)
    }

    pub fn iter(&self) -> impl Iterator<Item = (&String, &FactValue)> {
        self.map.iter()
    }
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/// A semantic story event. Applications translate raw input into these; the
/// director never knows what "Enter" means.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StoryEvent {
    /// A user made a semantic choice, e.g. `"pool"`, `"crew"`.
    UserSelected(String),
    /// A named shell/application command, e.g. `"city"`.
    Command(String),
    PermissionApproved,
    PermissionRejected,
    Cancelled,
    /// Any other named event.
    Custom(String),
}

impl StoryEvent {
    pub fn user_selected(choice: impl Into<String>) -> Self {
        StoryEvent::UserSelected(choice.into())
    }
    pub fn command(cmd: impl Into<String>) -> Self {
        StoryEvent::Command(cmd.into())
    }
    pub fn custom(name: impl Into<String>) -> Self {
        StoryEvent::Custom(name.into())
    }

    /// A stable, human-readable label for traces and debug output.
    pub fn label(&self) -> String {
        match self {
            StoryEvent::UserSelected(s) => format!("user:{s}"),
            StoryEvent::Command(s) => format!("cmd:{s}"),
            StoryEvent::PermissionApproved => "permission:approved".into(),
            StoryEvent::PermissionRejected => "permission:rejected".into(),
            StoryEvent::Cancelled => "cancelled".into(),
            StoryEvent::Custom(s) => format!("custom:{s}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Actions and conditions
// ---------------------------------------------------------------------------

/// A semantic action run on beat entry or by an in-beat reaction.
#[derive(Debug, Clone, PartialEq)]
pub enum StoryAction {
    SetBool(String, bool),
    SetNumber(String, f32),
    SetText(String, String),
    /// Mount a named effect bundle (persists until unmounted).
    Mount(String),
    /// Unmount a named effect bundle.
    Unmount(String),
}

impl StoryAction {
    pub fn set_bool(key: impl Into<String>, v: bool) -> Self {
        StoryAction::SetBool(key.into(), v)
    }
    pub fn set_number(key: impl Into<String>, v: f32) -> Self {
        StoryAction::SetNumber(key.into(), v)
    }
    pub fn set_text(key: impl Into<String>, v: impl Into<String>) -> Self {
        StoryAction::SetText(key.into(), v.into())
    }
    pub fn mount(bundle: impl Into<String>) -> Self {
        StoryAction::Mount(bundle.into())
    }
    pub fn unmount(bundle: impl Into<String>) -> Self {
        StoryAction::Unmount(bundle.into())
    }
}

/// A transition guard, or an event matcher for a [`Reaction`].
#[derive(Debug, Clone, PartialEq)]
pub enum Condition {
    /// Fire when the beat has been active for at least this long.
    After(Duration),
    /// Fire on an exact event.
    On(StoryEvent),
    /// Fire on `UserSelected(name)`.
    OnUser(String),
    /// Fire on `Command(name)`.
    OnCommand(String),
    /// Fire while a fact has an exact value.
    FactIs(String, FactValue),
    /// Fire while a boolean fact is true.
    FactTrue(String),
}

impl Condition {
    pub fn after(d: Duration) -> Self {
        Condition::After(d)
    }
    pub fn on(e: StoryEvent) -> Self {
        Condition::On(e)
    }
    pub fn user(name: impl Into<String>) -> Self {
        Condition::OnUser(name.into())
    }
    pub fn command(name: impl Into<String>) -> Self {
        Condition::OnCommand(name.into())
    }
    pub fn fact_bool(key: impl Into<String>, v: bool) -> Self {
        Condition::FactIs(key.into(), FactValue::Bool(v))
    }
    pub fn fact_true(key: impl Into<String>) -> Self {
        Condition::FactTrue(key.into())
    }

    fn matches_event(&self, e: &StoryEvent) -> bool {
        match self {
            Condition::On(want) => want == e,
            Condition::OnUser(name) => matches!(e, StoryEvent::UserSelected(s) if s == name),
            Condition::OnCommand(name) => matches!(e, StoryEvent::Command(s) if s == name),
            _ => false,
        }
    }

    fn matches_facts(&self, facts: &Facts) -> bool {
        match self {
            Condition::FactIs(key, want) => facts.get(key) == Some(want),
            Condition::FactTrue(key) => facts.bool(key),
            _ => false,
        }
    }
}

/// A labelled arrow from one beat to another.
#[derive(Debug, Clone, PartialEq)]
pub struct Transition {
    pub condition: Condition,
    pub next: String,
}

/// An event-triggered endomorphism on the current beat: actions without entry
/// into another beat or resetting its clock. Only event conditions (`On`,
/// `OnUser`, `OnCommand`) are supported; [`Story::validate`] rejects others.
#[derive(Debug, Clone, PartialEq)]
pub struct Reaction {
    pub condition: Condition,
    pub actions: Vec<StoryAction>,
}

// ---------------------------------------------------------------------------
// Beat
// ---------------------------------------------------------------------------

/// A story state: facts to set, effects to run, and outgoing arrows.
#[derive(Debug, Clone)]
pub struct Beat {
    pub id: String,
    pub label: String,
    pub on_enter: Vec<StoryAction>,
    pub effects: Vec<Effect>,
    /// Event/user transitions are ignored before this much beat time elapses.
    pub min_duration: Duration,
    /// If set, the beat auto-advances to `default_next` after this long.
    pub default_after: Option<Duration>,
    pub default_next: Option<String>,
    pub transitions: Vec<Transition>,
    /// In-beat event reactions, evaluated in declaration order for each event.
    pub reactions: Vec<Reaction>,
    /// Terminal beats stop the director.
    pub terminal: bool,
}

impl Beat {
    pub fn new(id: impl Into<String>) -> Self {
        let id = id.into();
        Self {
            label: id.clone(),
            id,
            on_enter: Vec::new(),
            effects: Vec::new(),
            min_duration: Duration::ZERO,
            default_after: None,
            default_next: None,
            transitions: Vec::new(),
            reactions: Vec::new(),
            terminal: false,
        }
    }

    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.label = label.into();
        self
    }

    pub fn on_enter(mut self, action: StoryAction) -> Self {
        self.on_enter.push(action);
        self
    }

    pub fn effect(mut self, e: Effect) -> Self {
        self.effects.push(e);
        self
    }

    pub fn effects(mut self, es: impl IntoIterator<Item = Effect>) -> Self {
        self.effects.extend(es);
        self
    }

    pub fn min_duration(mut self, d: Duration) -> Self {
        self.min_duration = d;
        self
    }

    /// Auto-advance to `next` after `d` (when no earlier transition fires).
    pub fn after(mut self, d: Duration, next: impl Into<String>) -> Self {
        self.default_after = Some(d);
        self.default_next = Some(next.into());
        self
    }

    /// Add a guarded transition.
    pub fn transition(mut self, condition: Condition, next: impl Into<String>) -> Self {
        self.transitions.push(Transition {
            condition,
            next: next.into(),
        });
        self
    }

    /// React to an event without leaving this beat or resetting beat time.
    ///
    /// Reactions run before transition selection and are not gated by
    /// [`Self::min_duration`]. Actions run in declaration order; remounting a
    /// bundle restarts its local clock, as with an entry action.
    pub fn reaction(
        mut self,
        condition: Condition,
        actions: impl IntoIterator<Item = StoryAction>,
    ) -> Self {
        self.reactions.push(Reaction {
            condition,
            actions: actions.into_iter().collect(),
        });
        self
    }

    pub fn terminal(mut self) -> Self {
        self.terminal = true;
        self
    }
}

// ---------------------------------------------------------------------------
// Trace
// ---------------------------------------------------------------------------

/// One recorded `update` call: the exact timestep and the events it carried.
///
/// Recording steps (rather than timestamped events) makes replay exact: the
/// director's semantics are a pure function of the ordered sequence of
/// `(dt, events)` updates, so replaying the steps reproduces the identical state
/// regardless of cadence.
#[derive(Debug, Clone, PartialEq)]
pub struct TraceStep {
    pub dt: Duration,
    pub events: Vec<StoryEvent>,
}

/// A recorded sequence of `update` calls and entered beats, for exact replay.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct StoryTrace {
    /// Every `update(dt, events)` call, in order.
    pub steps: Vec<TraceStep>,
    /// Every entered beat with the elapsed time at entry.
    pub beats: Vec<(Duration, String)>,
}

impl StoryTrace {
    pub fn record_beat(&mut self, at: Duration, beat: impl Into<String>) {
        self.beats.push((at, beat.into()));
    }

    /// The sequence of entered beats (including the start beat).
    pub fn beat_sequence(&self) -> Vec<&str> {
        self.beats.iter().map(|(_, b)| b.as_str()).collect()
    }

    /// Total elapsed time covered by the recorded steps.
    pub fn duration(&self) -> Duration {
        self.steps.iter().map(|s| s.dt).sum()
    }
}

// ---------------------------------------------------------------------------
// Story + Director
// ---------------------------------------------------------------------------

/// A malformed story definition.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StoryError {
    /// The start beat is not defined.
    UnknownStart(String),
    /// A transition points at a beat that does not exist.
    UnknownTarget { from: String, to: String },
    /// `default_after` is set without a valid `default_next`.
    MissingDefaultTarget(String),
    /// A mounted bundle name is not defined.
    UnknownBundle { beat: String, bundle: String },
    /// A reaction uses a timer or fact condition instead of an event matcher.
    InvalidReactionCondition { beat: String, reaction: usize },
}

impl std::fmt::Display for StoryError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StoryError::UnknownStart(s) => write!(f, "start beat `{s}` is not defined"),
            StoryError::UnknownTarget { from, to } => {
                write!(f, "beat `{from}` transitions to unknown beat `{to}`")
            }
            StoryError::MissingDefaultTarget(s) => {
                write!(f, "beat `{s}` has default_after but no valid default_next")
            }
            StoryError::UnknownBundle { beat, bundle } => {
                write!(f, "beat `{beat}` mounts unknown bundle `{bundle}`")
            }
            StoryError::InvalidReactionCondition { beat, reaction } => {
                write!(
                    f,
                    "beat `{beat}` reaction {reaction} requires an event condition"
                )
            }
        }
    }
}

/// An immutable story definition: beats and their effect bundles.
#[derive(Debug, Clone)]
pub struct Story {
    start: String,
    beats: BTreeMap<String, Beat>,
    bundles: BTreeMap<String, EffectBundle>,
}

impl Story {
    pub fn new(start: impl Into<String>) -> Self {
        Self {
            start: start.into(),
            beats: BTreeMap::new(),
            bundles: BTreeMap::new(),
        }
    }

    /// Adds a beat. **Panics** on a duplicate beat id: a semantic graph must not
    /// silently redefine one of its objects.
    pub fn beat(mut self, beat: Beat) -> Self {
        assert!(
            !self.beats.contains_key(&beat.id),
            "duplicate beat id: `{}`",
            beat.id
        );
        self.beats.insert(beat.id.clone(), beat);
        self
    }

    /// Adds an effect bundle. **Panics** on a duplicate name.
    pub fn bundle(mut self, bundle: EffectBundle) -> Self {
        assert!(
            !self.bundles.contains_key(&bundle.name),
            "duplicate effect bundle: `{}`",
            bundle.name
        );
        self.bundles.insert(bundle.name.clone(), bundle);
        self
    }

    /// Schema validation for a story definition.
    ///
    /// Duplicate beats/bundles are impossible by construction (the builders
    /// panic). This checks reference integrity: the start beat and every
    /// transition/default target exists, and every mounted bundle is defined.
    pub fn validate(&self) -> Result<(), StoryError> {
        if !self.beats.contains_key(&self.start) {
            return Err(StoryError::UnknownStart(self.start.clone()));
        }
        for beat in self.beats.values() {
            for t in &beat.transitions {
                if !self.beats.contains_key(&t.next) {
                    return Err(StoryError::UnknownTarget {
                        from: beat.id.clone(),
                        to: t.next.clone(),
                    });
                }
            }
            if beat.default_after.is_some() {
                match &beat.default_next {
                    Some(n) if self.beats.contains_key(n) => {}
                    _ => return Err(StoryError::MissingDefaultTarget(beat.id.clone())),
                }
            }
            for (index, reaction) in beat.reactions.iter().enumerate() {
                if !matches!(
                    reaction.condition,
                    Condition::On(_) | Condition::OnUser(_) | Condition::OnCommand(_)
                ) {
                    return Err(StoryError::InvalidReactionCondition {
                        beat: beat.id.clone(),
                        reaction: index,
                    });
                }
            }
            for action in beat
                .on_enter
                .iter()
                .chain(beat.reactions.iter().flat_map(|reaction| &reaction.actions))
            {
                if let StoryAction::Mount(name) = action {
                    if !self.bundles.contains_key(name) {
                        return Err(StoryError::UnknownBundle {
                            beat: beat.id.clone(),
                            bundle: name.clone(),
                        });
                    }
                }
            }
        }
        Ok(())
    }

    /// Creates a fresh director at the start beat.
    pub fn start(&self) -> StoryDirector {
        let mut d = StoryDirector {
            story: self.clone(),
            current: self.start.clone(),
            elapsed: Duration::ZERO,
            time_in_beat: Duration::ZERO,
            facts: Facts::new(),
            mounted: BTreeMap::new(),
            trace: StoryTrace::default(),
            finished: false,
        };
        // Run the start beat's on_enter actions and record it.
        if let Some(start) = self.beats.get(&self.start).cloned() {
            d.apply_actions(&start.on_enter);
            d.trace.record_beat(Duration::ZERO, self.start.clone());
            d.finished = start.terminal;
        } else {
            d.finished = true;
        }
        d
    }

    /// Exact replay: re-applies every recorded `update` step in order.
    ///
    /// Because [`StoryDirector::update`] is a pure function of
    /// `(story, ordered (dt, events) steps)`, replay reproduces the identical
    /// state — same beat sequence, facts, mounted bundles and final beat — for
    /// **any** original cadence, including irregular timesteps. This is stronger
    /// than replaying timestamped events onto a new grid.
    ///
    /// This contract covers changes made through recorded updates. Direct calls
    /// to [`StoryDirector::facts_mut`] or [`StoryDirector::jump_to`] are not
    /// recorded. Define inspection stages as the story's start beat with complete
    /// entry actions, and use reactions for replayable runtime mutations.
    pub fn replay(&self, trace: &StoryTrace) -> StoryDirector {
        let mut d = self.start();
        for step in &trace.steps {
            if d.is_finished() {
                break;
            }
            d.update(step.dt, &step.events);
        }
        d
    }
}

/// Owns current beat, beat time, facts, mounted bundles, an event queue and a trace.
#[derive(Debug, Clone)]
pub struct StoryDirector {
    story: Story,
    current: String,
    elapsed: Duration,
    time_in_beat: Duration,
    facts: Facts,
    mounted: BTreeMap<String, Duration>,
    trace: StoryTrace,
    finished: bool,
}

impl StoryDirector {
    /// The current beat id.
    pub fn current_beat(&self) -> &str {
        &self.current
    }

    /// The current beat's human label (falls back to the id).
    pub fn beat_label(&self) -> &str {
        self.story
            .beats
            .get(&self.current)
            .map(|b| b.label.as_str())
            .unwrap_or(&self.current)
    }

    /// Total elapsed time since the director started.
    pub fn elapsed(&self) -> Duration {
        self.elapsed
    }

    /// Time spent in the current beat.
    pub fn time_in_beat(&self) -> Duration {
        self.time_in_beat
    }

    pub fn facts(&self) -> &Facts {
        &self.facts
    }

    /// Mutate facts outside the event model. These changes are **not** recorded
    /// in [`StoryTrace`]; prefer [`Beat::reaction`] when exact replay is required.
    pub fn facts_mut(&mut self) -> &mut Facts {
        &mut self.facts
    }

    pub fn is_finished(&self) -> bool {
        self.finished
    }

    pub fn mounted(&self) -> impl Iterator<Item = &str> {
        self.mounted.keys().map(|s| s.as_str())
    }

    pub fn trace(&self) -> &StoryTrace {
        &self.trace
    }

    /// Advances time, applies events, and follows **at most one transition**.
    ///
    /// # Semantics (the one-arrow law)
    ///
    /// A single `update` follows at most one arrow between beats. Reactions are
    /// endomorphisms and do not count as beat transitions. Concretely:
    ///
    /// * Every event is trace-recorded in input order.
    /// * All matching reactions on the **original** beat run, in event order,
    ///   then reaction declaration order, then action order. Reactions do not
    ///   reset beat time and ignore `min_duration`. They match events only;
    ///   facts and timers are reserved for transition conditions.
    /// * The **first** event (in order) whose condition selects an outgoing arrow
    ///   from the current beat triggers exactly one transition. Once a transition
    ///   fires, no further transition is evaluated this update — including a
    ///   fact, `After(0)` or default transition on the *newly entered* beat.
    /// * No events are re-applied to the new beat. Even events after the winning
    ///   transition event have already run their reactions on the original beat.
    /// * If no event transition fires, at most one automatic transition (fact,
    ///   `After`, or `default_after`) may fire.
    ///   Fact guards observe the facts after **all** reactions. Explicit guards
    ///   use declaration order, followed by `default_after`. Entry actions on
    ///   the new beat run last and can overwrite reaction facts or mounts.
    ///
    /// Event transitions are gated by the current beat's [`Beat::min_duration`].
    ///
    /// This guarantees every entered beat is observable for at least one update,
    /// and it makes `After(Duration::ZERO)` a deliberate one-frame beat rather
    /// than an accidental collapse. Epsilon/immediate chaining is intentionally
    /// **not** provided.
    ///
    /// Deterministic given `(story, ordered dt/events sequence)`.
    pub fn update(&mut self, dt: Duration, events: &[StoryEvent]) {
        if self.finished {
            return;
        }
        self.elapsed = self.elapsed.saturating_add(dt);
        self.time_in_beat = self.time_in_beat.saturating_add(dt);

        // Record the exact step so replay can reproduce this call precisely.
        self.trace.steps.push(TraceStep {
            dt,
            events: events.to_vec(),
        });

        // Freeze the reaction definitions, not the facts: every event is handled
        // by the original beat before any outgoing transition is selected.
        if let Some(beat) = self
            .story
            .beats
            .get(&self.current)
            .filter(|_| !events.is_empty())
        {
            let reactions = beat.reactions.clone();
            for event in events {
                for reaction in &reactions {
                    if reaction.condition.matches_event(event) {
                        self.apply_actions(&reaction.actions);
                    }
                }
            }
        }

        // At most one arrow: the first matching event transition wins.
        if !events.is_empty() && self.time_in_beat >= self.min_duration() {
            if let Some(next) = events.iter().find_map(|e| self.find_event_transition(e)) {
                self.enter(next);
                return;
            }
        }

        // Otherwise at most one automatic transition.
        if let Some(next) = self.find_auto_transition() {
            self.enter(next);
        }
    }

    fn min_duration(&self) -> Duration {
        self.story
            .beats
            .get(&self.current)
            .map(|b| b.min_duration)
            .unwrap_or(Duration::ZERO)
    }

    fn find_event_transition(&self, e: &StoryEvent) -> Option<String> {
        let beat = self.story.beats.get(&self.current)?;
        beat.transitions
            .iter()
            .find(|t| t.condition.matches_event(e))
            .map(|t| t.next.clone())
    }

    fn find_auto_transition(&self) -> Option<String> {
        let beat = self.story.beats.get(&self.current)?;
        // Explicit fact/After guards share declaration order, then the default.
        for t in &beat.transitions {
            match &t.condition {
                Condition::FactIs(..) | Condition::FactTrue(..)
                    if self.time_in_beat >= beat.min_duration
                        && t.condition.matches_facts(&self.facts) =>
                {
                    return Some(t.next.clone());
                }
                Condition::After(d) if self.time_in_beat >= *d => {
                    return Some(t.next.clone());
                }
                _ => {}
            }
        }
        if let Some(after) = beat.default_after {
            if self.time_in_beat >= after {
                return beat.default_next.clone();
            }
        }
        None
    }

    fn enter(&mut self, next: String) {
        let Some(beat) = self.story.beats.get(&next).cloned() else {
            // Unknown target: treat as the end of the story rather than looping.
            self.finished = true;
            return;
        };
        self.current = next;
        self.time_in_beat = Duration::ZERO;
        self.apply_actions(&beat.on_enter);
        self.trace.record_beat(self.elapsed, self.current.clone());
        if beat.terminal {
            self.finished = true;
        }
    }

    fn apply_actions(&mut self, actions: &[StoryAction]) {
        for action in actions {
            match action {
                StoryAction::SetBool(k, v) => self.facts.set_bool(k.clone(), *v),
                StoryAction::SetNumber(k, v) => self.facts.set_number(k.clone(), *v),
                StoryAction::SetText(k, v) => self.facts.set_text(k.clone(), v.clone()),
                StoryAction::Mount(name) => {
                    self.mounted.insert(name.clone(), self.elapsed);
                }
                StoryAction::Unmount(name) => {
                    self.mounted.remove(name);
                }
            }
        }
    }

    /// Evaluates the current beat's effects and every mounted bundle.
    ///
    /// Beat effects run on beat-local time; bundle effects run on time since
    /// mount. Pure and deterministic.
    pub fn presentation(&self, scene: &Scene) -> Presentation {
        let mut p = Presentation::new();
        if let Some(beat) = self.story.beats.get(&self.current) {
            for e in &beat.effects {
                e.eval(self.time_in_beat, scene, &mut p);
            }
        }
        for (name, mount_t) in &self.mounted {
            if let Some(bundle) = self.story.bundles.get(name) {
                let t = self.elapsed.saturating_sub(*mount_t);
                for e in &bundle.effects {
                    e.eval(t, scene, &mut p);
                }
            }
        }
        p
    }

    /// Jumps directly to a beat, running its `on_enter` actions.
    ///
    /// This is the deterministic "start state" hook for tests, goldens and
    /// `--stage=` flags (analogous to the Hackers `--act=` jump). Returns `false`
    /// if the beat is unknown.
    ///
    /// This jump is not an update step and cannot be reproduced by trace replay.
    /// For replayable stage inspection, construct a story starting at that beat
    /// with entry actions establishing the complete initial state.
    pub fn jump_to(&mut self, beat: impl AsRef<str>) -> bool {
        let id = beat.as_ref().to_string();
        if self.story.beats.contains_key(&id) {
            self.finished = false;
            self.enter(id);
            true
        } else {
            false
        }
    }

    /// A compact debug inspector: current beat, facts, mounted bundles and time.
    pub fn debug_lines(&self) -> Vec<String> {
        let mut out = vec![format!(
            "beat {} ({:.2}s / {:.2}s)",
            self.current,
            self.time_in_beat.as_secs_f32(),
            self.elapsed.as_secs_f32()
        )];
        for (k, v) in self.facts.iter() {
            out.push(format!("  fact {k} = {v:?}"));
        }
        for m in self.mounted() {
            out.push(format!("  mounted {m}"));
        }
        out
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cell::Style;
    use crate::node::Node;
    use crate::scene::SceneEntity;

    fn ms(n: u64) -> Duration {
        Duration::from_millis(n)
    }

    fn text(label: &str) -> Node {
        Node::text(label, Style::default()).width(4.0).height(1.0)
    }

    /// A branch/join story mirroring the tactical-choice shape.
    fn tactical_story() -> Story {
        Story::new("tactical")
            .beat(
                Beat::new("tactical")
                    .min_duration(ms(50))
                    .transition(Condition::user("pool"), "pool")
                    .transition(Condition::user("crew"), "crew")
                    .after(ms(500), "download"),
            )
            .beat(
                Beat::new("pool")
                    .on_enter(StoryAction::set_bool("pool-distraction", true))
                    .after(ms(100), "download"),
            )
            .beat(
                Beat::new("crew")
                    .on_enter(StoryAction::set_bool("crew-reinforced", true))
                    .after(ms(100), "download"),
            )
            .beat(Beat::new("download").terminal())
    }

    #[test]
    fn default_timeout_path_reaches_download() {
        let story = tactical_story();
        let mut d = story.start();
        for _ in 0..60 {
            d.update(ms(10), &[]);
        }
        assert_eq!(d.current_beat(), "download");
        assert!(!d.facts().bool("pool-distraction"));
        assert!(!d.facts().bool("crew-reinforced"));
    }

    #[test]
    fn user_choice_after_min_duration_selects_the_arrow() {
        let story = tactical_story();
        let mut d = story.start();
        d.update(ms(10), &[]);
        // Too early: ignored by min_duration.
        d.update(ms(10), &[StoryEvent::user_selected("pool")]);
        assert_eq!(d.current_beat(), "tactical");
        // Past min duration: selects the Pool arrow.
        d.update(ms(50), &[StoryEvent::user_selected("pool")]);
        assert_eq!(d.current_beat(), "pool");
        assert!(d.facts().bool("pool-distraction"));
    }

    #[test]
    fn branches_differ_locally_but_reconverge() {
        let story = tactical_story();

        let mut pool = story.start();
        pool.update(ms(60), &[StoryEvent::user_selected("pool")]);
        let mut crew = story.start();
        crew.update(ms(60), &[StoryEvent::user_selected("crew")]);

        // Local facts differ.
        assert!(pool.facts().bool("pool-distraction"));
        assert!(!pool.facts().bool("crew-reinforced"));
        assert!(crew.facts().bool("crew-reinforced"));
        assert!(!crew.facts().bool("pool-distraction"));

        // Both reconverge at Download.
        for _ in 0..20 {
            pool.update(ms(10), &[]);
            crew.update(ms(10), &[]);
        }
        assert_eq!(pool.current_beat(), "download");
        assert_eq!(crew.current_beat(), "download");
    }

    #[test]
    fn mounted_bundles_run_on_time_since_mount() {
        let story = Story::new("a")
            .bundle(EffectBundle::new("plague").effect(Effect::set_custom(
                crate::scene::SceneTarget::Id(crate::scene::SceneId(0)),
                7,
                1.0,
            )))
            .beat(
                Beat::new("a")
                    .on_enter(StoryAction::mount("plague"))
                    .after(ms(100), "b"),
            )
            .beat(
                Beat::new("b")
                    .on_enter(StoryAction::unmount("plague"))
                    .terminal(),
            );
        let mut d = story.start();
        assert!(d.mounted().any(|m| m == "plague"));
        d.update(ms(50), &[]);
        assert_eq!(d.current_beat(), "a");
        d.update(ms(60), &[]);
        assert_eq!(d.current_beat(), "b");
        assert!(!d.mounted().any(|m| m == "plague"));
    }

    #[test]
    fn story_replay_is_deterministic_and_identical() {
        let story = tactical_story();
        let mut d = story.start();
        d.update(ms(60), &[StoryEvent::user_selected("crew")]);
        for _ in 0..20 {
            d.update(ms(10), &[]);
        }
        let original = d.trace().beat_sequence().join(">");

        let replayed = story.replay(d.trace());
        let replay_seq = replayed.trace().beat_sequence().join(">");
        assert_eq!(original, replay_seq);
        assert_eq!(replayed.current_beat(), d.current_beat());
    }

    #[test]
    fn replay_reproduces_irregular_dt_exactly() {
        // Option B contract: the trace records the exact (dt, events) updates, so
        // replay reproduces any cadence — including irregular timesteps.
        let story = tactical_story();
        let dts = [ms(7), ms(13), ms(41), ms(3), ms(60), ms(5), ms(22), ms(9)];
        let mut d = story.start();
        for (i, dt) in dts.iter().enumerate() {
            let evs: Vec<StoryEvent> = if i == 4 {
                vec![StoryEvent::user_selected("pool")]
            } else {
                vec![]
            };
            d.update(*dt, &evs);
            if d.is_finished() {
                break;
            }
        }

        let replayed = story.replay(d.trace());
        assert_eq!(replayed.current_beat(), d.current_beat());
        assert_eq!(
            replayed.trace().beat_sequence(),
            d.trace().beat_sequence(),
            "entered-beat sequence must match"
        );
        assert_eq!(
            replayed.facts().bool("pool-distraction"),
            d.facts().bool("pool-distraction")
        );
        assert_eq!(replayed.mounted().count(), d.mounted().count());
    }

    // -----------------------------------------------------------------------
    // One-arrow law.
    // -----------------------------------------------------------------------

    #[test]
    fn event_then_immediate_beat_is_observable() {
        // A --go--> B ; B --After(0)--> C : B must survive one update.
        let story = Story::new("a")
            .beat(
                Beat::new("a")
                    .transition(Condition::user("go"), "b")
                    .after(ms(1000), "c"),
            )
            .beat(Beat::new("b").after(Duration::ZERO, "c"))
            .beat(Beat::new("c").terminal());
        let mut d = story.start();
        d.update(ms(10), &[StoryEvent::user_selected("go")]);
        assert_eq!(d.current_beat(), "b", "B must be observable for one update");
        d.update(ms(10), &[]);
        assert_eq!(d.current_beat(), "c");
    }

    #[test]
    fn multiple_events_only_the_first_transitions() {
        let story = Story::new("a")
            .beat(
                Beat::new("a")
                    .transition(Condition::user("foo"), "b")
                    .after(ms(1000), "z"),
            )
            .beat(
                Beat::new("b")
                    .transition(Condition::user("bar"), "c")
                    .after(ms(1000), "z"),
            )
            .beat(Beat::new("c").terminal())
            .beat(Beat::new("z").terminal());
        let mut d = story.start();
        d.update(
            ms(10),
            &[
                StoryEvent::user_selected("foo"),
                StoryEvent::user_selected("bar"),
            ],
        );
        // Only `foo` drives a transition; `bar` must not chain into C.
        assert_eq!(d.current_beat(), "b");
        // Both events were trace-recorded.
        assert_eq!(d.trace().steps[0].events.len(), 2);
    }

    #[test]
    fn fact_transition_waits_for_next_update() {
        let story = Story::new("a")
            .beat(
                Beat::new("a")
                    .transition(Condition::user("go"), "b")
                    .after(ms(1000), "c"),
            )
            .beat(
                Beat::new("b")
                    .on_enter(StoryAction::set_bool("ready", true))
                    .transition(Condition::fact_true("ready"), "c")
                    .after(ms(1000), "z"),
            )
            .beat(Beat::new("c").terminal())
            .beat(Beat::new("z").terminal());
        let mut d = story.start();
        d.update(ms(10), &[StoryEvent::user_selected("go")]);
        assert_eq!(d.current_beat(), "b");
        assert!(d.facts().bool("ready"));
        d.update(ms(1), &[]);
        assert_eq!(d.current_beat(), "c");
    }

    #[test]
    fn trace_records_every_intermediate_beat() {
        let story = Story::new("a")
            .beat(
                Beat::new("a")
                    .transition(Condition::user("go"), "b")
                    .after(ms(1000), "c"),
            )
            .beat(Beat::new("b").after(Duration::ZERO, "c"))
            .beat(Beat::new("c").terminal());
        let mut d = story.start();
        d.update(ms(10), &[StoryEvent::user_selected("go")]);
        d.update(ms(10), &[]);
        assert_eq!(d.trace().beat_sequence(), vec!["a", "b", "c"]);
    }

    // -----------------------------------------------------------------------
    // Graph integrity.
    // -----------------------------------------------------------------------

    #[test]
    #[should_panic(expected = "duplicate beat id")]
    fn duplicate_beat_ids_are_rejected() {
        let _ = Story::new("a").beat(Beat::new("a")).beat(Beat::new("a"));
    }

    #[test]
    #[should_panic(expected = "duplicate effect bundle")]
    fn duplicate_bundle_names_are_rejected() {
        let _ = Story::new("a")
            .bundle(EffectBundle::new("fx"))
            .bundle(EffectBundle::new("fx"))
            .beat(Beat::new("a"));
    }

    #[test]
    fn validate_accepts_a_well_formed_story() {
        assert!(tactical_story().validate().is_ok());
    }

    #[test]
    fn validate_rejects_unknown_start() {
        let s = Story::new("missing").beat(Beat::new("a"));
        assert_eq!(
            s.validate(),
            Err(StoryError::UnknownStart("missing".into()))
        );
    }

    #[test]
    fn validate_rejects_unknown_transition_target() {
        let s = Story::new("a").beat(Beat::new("a").transition(Condition::user("x"), "nope"));
        assert_eq!(
            s.validate(),
            Err(StoryError::UnknownTarget {
                from: "a".into(),
                to: "nope".into()
            })
        );
    }

    #[test]
    fn validate_rejects_missing_default_target() {
        // default_after set, default_next absent.
        let mut beat = Beat::new("a");
        beat.default_after = Some(ms(10));
        let s = Story::new("a").beat(beat);
        assert_eq!(
            s.validate(),
            Err(StoryError::MissingDefaultTarget("a".into()))
        );
    }

    #[test]
    fn validate_rejects_unknown_mounted_bundle() {
        let s = Story::new("a").beat(Beat::new("a").on_enter(StoryAction::mount("ghost")));
        assert_eq!(
            s.validate(),
            Err(StoryError::UnknownBundle {
                beat: "a".into(),
                bundle: "ghost".into()
            })
        );
    }

    #[test]
    fn facts_are_semantic_and_persistent() {
        let story = Story::new("a")
            .beat(
                Beat::new("a")
                    .on_enter(StoryAction::set_bool("plague-active", true))
                    .after(ms(10), "b"),
            )
            .beat(Beat::new("b").after(ms(10), "c"))
            .beat(Beat::new("c").terminal());
        let mut d = story.start();
        d.update(ms(15), &[]);
        assert_eq!(d.current_beat(), "b");
        assert!(
            d.facts().bool("plague-active"),
            "fact persists across beats"
        );
        d.update(ms(15), &[]);
        assert_eq!(d.current_beat(), "c");
        assert!(d.facts().bool("plague-active"), "fact still persists");
    }

    #[test]
    fn presentation_composes_beat_and_bundle_effects() {
        let mut scene = Scene::new();
        let a = scene.add(SceneEntity::new("a", text("a")));
        let t = crate::scene::SceneTarget::Id(a);
        let story = Story::new("a")
            .bundle(EffectBundle::new("b").effect(Effect::translate(
                t,
                (0.0, 0.0),
                (5.0, 0.0),
                ms(100),
            )))
            .beat(
                Beat::new("a")
                    .on_enter(StoryAction::mount("b"))
                    .effect(Effect::set_custom(t, 1, 2.0))
                    .after(ms(200), "z"),
            )
            .beat(Beat::new("z").terminal());
        let mut d = story.start();
        d.update(ms(50), &[]);
        let p = d.presentation(&scene);
        assert_eq!(p.offset_of(&scene, a), (3, 0)); // 2.5 rounds to 3
        assert_eq!(p.custom(a, 1), Some(2.0)); // beat effect
    }

    #[test]
    fn debug_inspector_reports_beat_facts_and_mounts() {
        let story = Story::new("a")
            .bundle(EffectBundle::new("fx").effect(Effect::identity()))
            .beat(
                Beat::new("a")
                    .label("Arrival")
                    .on_enter(StoryAction::set_bool("seen", true))
                    .on_enter(StoryAction::mount("fx"))
                    .terminal(),
            );
        let d = story.start();
        let lines = d.debug_lines();
        assert!(lines[0].contains("a"));
        assert!(lines.iter().any(|l| l.contains("seen")));
        assert!(lines.iter().any(|l| l.contains("mounted fx")));
        assert_eq!(d.beat_label(), "Arrival");
    }
}
