//! Story Director — semantic world state and beat progression.
//!
//! The narrative layer is modelled as a graph of [`Beat`]s. Each beat is an
//! object; each allowed transition is a generating morphism; a playable session
//! is a path through the free category generated by that graph. A user choice
//! selects a different arrow without exploding the application state machine,
//! and branches may reconverge later.
//!
//! Crucially, narrative truth is stored as [`Facts`] — semantic world state —
//! **not** as countdown timers. `PlagueActive = true` stays true until something
//! explicitly clears it, so scene effects can attach to the fact rather than
//! being manually refreshed every frame.
//!
//! The director owns: the current beat, beat time, facts, mounted effect bundles,
//! an event queue and an optional [`StoryTrace`] for deterministic replay. It
//! does **not** own the terminal, `Context`, input polling, ANSI or layout — the
//! application converts keyboard input into semantic [`StoryEvent`]s and calls
//! [`StoryDirector::update`].

use crate::scene::{Effect, EffectBundle, Presentation, Scene};
use std::collections::BTreeMap;
use std::time::Duration;

// ---------------------------------------------------------------------------
// Facts
// ---------------------------------------------------------------------------

/// A typed fact value.
#[derive(Debug, Clone, PartialEq)]
pub enum FactValue {
    Bool(bool),
    Number(f32),
    Text(String),
}

impl FactValue {
    fn as_bool(&self) -> Option<bool> {
        match self {
            FactValue::Bool(b) => Some(*b),
            _ => None,
        }
    }
    fn as_number(&self) -> Option<f32> {
        match self {
            FactValue::Number(n) => Some(*n),
            _ => None,
        }
    }
    fn as_text(&self) -> Option<&str> {
        match self {
            FactValue::Text(s) => Some(s),
            _ => None,
        }
    }
}

/// Semantic world state keyed by name.
///
/// Absent booleans read as `false`, absent numbers as `0.0`, absent text as `""`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Facts {
    map: BTreeMap<String, FactValue>,
}

impl Facts {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn set_bool(&mut self, key: impl Into<String>, v: bool) {
        self.map.insert(key.into(), FactValue::Bool(v));
    }

    pub fn set_number(&mut self, key: impl Into<String>, v: f32) {
        self.map.insert(key.into(), FactValue::Number(v));
    }

    pub fn set_text(&mut self, key: impl Into<String>, v: impl Into<String>) {
        self.map.insert(key.into(), FactValue::Text(v.into()));
    }

    pub fn bool(&self, key: &str) -> bool {
        self.map
            .get(key)
            .and_then(FactValue::as_bool)
            .unwrap_or(false)
    }

    pub fn number(&self, key: &str) -> f32 {
        self.map
            .get(key)
            .and_then(FactValue::as_number)
            .unwrap_or(0.0)
    }

    pub fn text(&self, key: &str) -> &str {
        self.map.get(key).and_then(FactValue::as_text).unwrap_or("")
    }

    pub fn get(&self, key: &str) -> Option<&FactValue> {
        self.map.get(key)
    }

    pub fn iter(&self) -> impl Iterator<Item = (&String, &FactValue)> {
        self.map.iter()
    }
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/// A semantic story event. Applications translate raw input into these; the
/// director never knows what "Enter" means.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StoryEvent {
    /// A user made a semantic choice, e.g. `"pool"`, `"crew"`.
    UserSelected(String),
    /// A named shell/application command, e.g. `"city"`.
    Command(String),
    PermissionApproved,
    PermissionRejected,
    Cancelled,
    /// Any other named event.
    Custom(String),
}

impl StoryEvent {
    pub fn user_selected(choice: impl Into<String>) -> Self {
        StoryEvent::UserSelected(choice.into())
    }
    pub fn command(cmd: impl Into<String>) -> Self {
        StoryEvent::Command(cmd.into())
    }
    pub fn custom(name: impl Into<String>) -> Self {
        StoryEvent::Custom(name.into())
    }

    /// A stable, human-readable label for traces and debug output.
    pub fn label(&self) -> String {
        match self {
            StoryEvent::UserSelected(s) => format!("user:{s}"),
            StoryEvent::Command(s) => format!("cmd:{s}"),
            StoryEvent::PermissionApproved => "permission:approved".into(),
            StoryEvent::PermissionRejected => "permission:rejected".into(),
            StoryEvent::Cancelled => "cancelled".into(),
            StoryEvent::Custom(s) => format!("custom:{s}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Actions and conditions
// ---------------------------------------------------------------------------

/// A side effect run when a beat is entered.
#[derive(Debug, Clone, PartialEq)]
pub enum StoryAction {
    SetBool(String, bool),
    SetNumber(String, f32),
    SetText(String, String),
    /// Mount a named effect bundle (persists until unmounted).
    Mount(String),
    /// Unmount a named effect bundle.
    Unmount(String),
}

impl StoryAction {
    pub fn set_bool(key: impl Into<String>, v: bool) -> Self {
        StoryAction::SetBool(key.into(), v)
    }
    pub fn set_number(key: impl Into<String>, v: f32) -> Self {
        StoryAction::SetNumber(key.into(), v)
    }
    pub fn set_text(key: impl Into<String>, v: impl Into<String>) -> Self {
        StoryAction::SetText(key.into(), v.into())
    }
    pub fn mount(bundle: impl Into<String>) -> Self {
        StoryAction::Mount(bundle.into())
    }
    pub fn unmount(bundle: impl Into<String>) -> Self {
        StoryAction::Unmount(bundle.into())
    }
}

/// A transition guard.
#[derive(Debug, Clone, PartialEq)]
pub enum Condition {
    /// Fire when the beat has been active for at least this long.
    After(Duration),
    /// Fire on an exact event.
    On(StoryEvent),
    /// Fire on `UserSelected(name)`.
    OnUser(String),
    /// Fire on `Command(name)`.
    OnCommand(String),
    /// Fire while a fact has an exact value.
    FactIs(String, FactValue),
    /// Fire while a boolean fact is true.
    FactTrue(String),
}

impl Condition {
    pub fn after(d: Duration) -> Self {
        Condition::After(d)
    }
    pub fn on(e: StoryEvent) -> Self {
        Condition::On(e)
    }
    pub fn user(name: impl Into<String>) -> Self {
        Condition::OnUser(name.into())
    }
    pub fn command(name: impl Into<String>) -> Self {
        Condition::OnCommand(name.into())
    }
    pub fn fact_bool(key: impl Into<String>, v: bool) -> Self {
        Condition::FactIs(key.into(), FactValue::Bool(v))
    }
    pub fn fact_true(key: impl Into<String>) -> Self {
        Condition::FactTrue(key.into())
    }

    fn matches_event(&self, e: &StoryEvent) -> bool {
        match self {
            Condition::On(want) => want == e,
            Condition::OnUser(name) => matches!(e, StoryEvent::UserSelected(s) if s == name),
            Condition::OnCommand(name) => matches!(e, StoryEvent::Command(s) if s == name),
            _ => false,
        }
    }

    fn matches_facts(&self, facts: &Facts) -> bool {
        match self {
            Condition::FactIs(key, want) => facts.get(key) == Some(want),
            Condition::FactTrue(key) => facts.bool(key),
            _ => false,
        }
    }
}

/// A labelled arrow from one beat to another.
#[derive(Debug, Clone, PartialEq)]
pub struct Transition {
    pub condition: Condition,
    pub next: String,
}

// ---------------------------------------------------------------------------
// Beat
// ---------------------------------------------------------------------------

/// A story state: facts to set, effects to run, and outgoing arrows.
#[derive(Debug, Clone)]
pub struct Beat {
    pub id: String,
    pub label: String,
    pub on_enter: Vec<StoryAction>,
    pub effects: Vec<Effect>,
    /// Event/user transitions are ignored before this much beat time elapses.
    pub min_duration: Duration,
    /// If set, the beat auto-advances to `default_next` after this long.
    pub default_after: Option<Duration>,
    pub default_next: Option<String>,
    pub transitions: Vec<Transition>,
    /// Terminal beats stop the director.
    pub terminal: bool,
}

impl Beat {
    pub fn new(id: impl Into<String>) -> Self {
        let id = id.into();
        Self {
            label: id.clone(),
            id,
            on_enter: Vec::new(),
            effects: Vec::new(),
            min_duration: Duration::ZERO,
            default_after: None,
            default_next: None,
            transitions: Vec::new(),
            terminal: false,
        }
    }

    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.label = label.into();
        self
    }

    pub fn on_enter(mut self, action: StoryAction) -> Self {
        self.on_enter.push(action);
        self
    }

    pub fn effect(mut self, e: Effect) -> Self {
        self.effects.push(e);
        self
    }

    pub fn effects(mut self, es: impl IntoIterator<Item = Effect>) -> Self {
        self.effects.extend(es);
        self
    }

    pub fn min_duration(mut self, d: Duration) -> Self {
        self.min_duration = d;
        self
    }

    /// Auto-advance to `next` after `d` (when no earlier transition fires).
    pub fn after(mut self, d: Duration, next: impl Into<String>) -> Self {
        self.default_after = Some(d);
        self.default_next = Some(next.into());
        self
    }

    /// Add a guarded transition.
    pub fn transition(mut self, condition: Condition, next: impl Into<String>) -> Self {
        self.transitions.push(Transition {
            condition,
            next: next.into(),
        });
        self
    }

    pub fn terminal(mut self) -> Self {
        self.terminal = true;
        self
    }
}

// ---------------------------------------------------------------------------
// Trace
// ---------------------------------------------------------------------------

/// A recorded sequence of events and entered beats, for deterministic replay.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct StoryTrace {
    pub events: Vec<(Duration, StoryEvent)>,
    pub beats: Vec<(Duration, String)>,
}

impl StoryTrace {
    pub fn record(&mut self, at: Duration, e: StoryEvent) {
        self.events.push((at, e));
    }

    pub fn record_beat(&mut self, at: Duration, beat: impl Into<String>) {
        self.beats.push((at, beat.into()));
    }

    pub fn beat_sequence(&self) -> Vec<&str> {
        self.beats.iter().map(|(_, b)| b.as_str()).collect()
    }
}

// ---------------------------------------------------------------------------
// Story + Director
// ---------------------------------------------------------------------------

/// An immutable story definition: beats and their effect bundles.
#[derive(Debug, Clone)]
pub struct Story {
    start: String,
    beats: BTreeMap<String, Beat>,
    bundles: BTreeMap<String, EffectBundle>,
}

impl Story {
    pub fn new(start: impl Into<String>) -> Self {
        Self {
            start: start.into(),
            beats: BTreeMap::new(),
            bundles: BTreeMap::new(),
        }
    }

    pub fn beat(mut self, beat: Beat) -> Self {
        self.beats.insert(beat.id.clone(), beat);
        self
    }

    pub fn bundle(mut self, bundle: EffectBundle) -> Self {
        self.bundles.insert(bundle.name.clone(), bundle);
        self
    }

    /// Creates a fresh director at the start beat.
    pub fn start(&self) -> StoryDirector {
        let mut d = StoryDirector {
            story: self.clone(),
            current: self.start.clone(),
            elapsed: Duration::ZERO,
            time_in_beat: Duration::ZERO,
            facts: Facts::new(),
            mounted: BTreeMap::new(),
            trace: StoryTrace::default(),
            finished: false,
        };
        // Run the start beat's on_enter actions and record it.
        if let Some(start) = self.beats.get(&self.start).cloned() {
            d.apply_actions(&start);
            d.trace.record_beat(Duration::ZERO, self.start.clone());
            d.finished = start.terminal;
        } else {
            d.finished = true;
        }
        d
    }

    /// Replays a trace with a fixed timestep and returns the resulting director.
    ///
    /// Deterministic: same story + same trace + same `dt` ⇒ identical state.
    pub fn replay(&self, trace: &StoryTrace, dt: Duration) -> StoryDirector {
        let mut d = self.start();
        if dt.is_zero() {
            return d;
        }
        let horizon = trace
            .events
            .iter()
            .map(|(t, _)| *t)
            .chain(trace.beats.iter().map(|(t, _)| *t))
            .max()
            .unwrap_or(Duration::ZERO)
            + dt;
        let mut frame: u64 = 1;
        while d.elapsed < horizon && !d.finished {
            let now = dt.saturating_mul(frame as u32);
            let evs: Vec<StoryEvent> = trace
                .events
                .iter()
                .filter(|(t, _)| *t == now)
                .map(|(_, e)| e.clone())
                .collect();
            d.update(dt, &evs);
            frame += 1;
        }
        d
    }
}

/// Owns current beat, beat time, facts, mounted bundles, an event queue and a trace.
#[derive(Debug, Clone)]
pub struct StoryDirector {
    story: Story,
    current: String,
    elapsed: Duration,
    time_in_beat: Duration,
    facts: Facts,
    mounted: BTreeMap<String, Duration>,
    trace: StoryTrace,
    finished: bool,
}

impl StoryDirector {
    /// The current beat id.
    pub fn current_beat(&self) -> &str {
        &self.current
    }

    /// The current beat's human label (falls back to the id).
    pub fn beat_label(&self) -> &str {
        self.story
            .beats
            .get(&self.current)
            .map(|b| b.label.as_str())
            .unwrap_or(&self.current)
    }

    /// Total elapsed time since the director started.
    pub fn elapsed(&self) -> Duration {
        self.elapsed
    }

    /// Time spent in the current beat.
    pub fn time_in_beat(&self) -> Duration {
        self.time_in_beat
    }

    pub fn facts(&self) -> &Facts {
        &self.facts
    }

    pub fn facts_mut(&mut self) -> &mut Facts {
        &mut self.facts
    }

    pub fn is_finished(&self) -> bool {
        self.finished
    }

    pub fn mounted(&self) -> impl Iterator<Item = &str> {
        self.mounted.keys().map(|s| s.as_str())
    }

    pub fn trace(&self) -> &StoryTrace {
        &self.trace
    }

    /// Advances time, applies events, and follows at most one transition.
    ///
    /// Deterministic given `(story, dt sequence, events)`. Event transitions are
    /// gated by the current beat's `min_duration`; timed and fact transitions are
    /// checked afterwards, so a beat with `min_duration == 0` can still advance
    /// on the same frame if nothing else fires.
    pub fn update(&mut self, dt: Duration, events: &[StoryEvent]) {
        if self.finished {
            return;
        }
        self.elapsed = self.elapsed.saturating_add(dt);
        self.time_in_beat = self.time_in_beat.saturating_add(dt);

        for e in events {
            self.trace.record(self.elapsed, e.clone());
            if self.time_in_beat >= self.min_duration() {
                if let Some(next) = self.find_event_transition(e) {
                    self.enter(next);
                    if self.finished {
                        return;
                    }
                }
            }
        }

        if let Some(next) = self.find_auto_transition() {
            self.enter(next);
        }
    }

    fn min_duration(&self) -> Duration {
        self.story
            .beats
            .get(&self.current)
            .map(|b| b.min_duration)
            .unwrap_or(Duration::ZERO)
    }

    fn find_event_transition(&self, e: &StoryEvent) -> Option<String> {
        let beat = self.story.beats.get(&self.current)?;
        beat.transitions
            .iter()
            .find(|t| t.condition.matches_event(e))
            .map(|t| t.next.clone())
    }

    fn find_auto_transition(&self) -> Option<String> {
        let beat = self.story.beats.get(&self.current)?;
        // Fact conditions next (in declaration order), then explicit `After`.
        for t in &beat.transitions {
            match &t.condition {
                Condition::FactIs(..) | Condition::FactTrue(..)
                    if self.time_in_beat >= beat.min_duration
                        && t.condition.matches_facts(&self.facts) =>
                {
                    return Some(t.next.clone());
                }
                Condition::After(d) if self.time_in_beat >= *d => {
                    return Some(t.next.clone());
                }
                _ => {}
            }
        }
        if let Some(after) = beat.default_after {
            if self.time_in_beat >= after {
                return beat.default_next.clone();
            }
        }
        None
    }

    fn enter(&mut self, next: String) {
        let Some(beat) = self.story.beats.get(&next).cloned() else {
            // Unknown target: treat as the end of the story rather than looping.
            self.finished = true;
            return;
        };
        self.current = next;
        self.time_in_beat = Duration::ZERO;
        self.apply_actions(&beat);
        self.trace.record_beat(self.elapsed, self.current.clone());
        if beat.terminal {
            self.finished = true;
        }
    }

    fn apply_actions(&mut self, beat: &Beat) {
        for action in &beat.on_enter {
            match action {
                StoryAction::SetBool(k, v) => self.facts.set_bool(k.clone(), *v),
                StoryAction::SetNumber(k, v) => self.facts.set_number(k.clone(), *v),
                StoryAction::SetText(k, v) => self.facts.set_text(k.clone(), v.clone()),
                StoryAction::Mount(name) => {
                    self.mounted.insert(name.clone(), self.elapsed);
                }
                StoryAction::Unmount(name) => {
                    self.mounted.remove(name);
                }
            }
        }
    }

    /// Evaluates the current beat's effects and every mounted bundle.
    ///
    /// Beat effects run on beat-local time; bundle effects run on time since
    /// mount. Pure and deterministic.
    pub fn presentation(&self, scene: &Scene) -> Presentation {
        let mut p = Presentation::new();
        if let Some(beat) = self.story.beats.get(&self.current) {
            for e in &beat.effects {
                e.eval(self.time_in_beat, scene, &mut p);
            }
        }
        for (name, mount_t) in &self.mounted {
            if let Some(bundle) = self.story.bundles.get(name) {
                let t = self.elapsed.saturating_sub(*mount_t);
                for e in &bundle.effects {
                    e.eval(t, scene, &mut p);
                }
            }
        }
        p
    }

    /// A compact debug inspector: current beat, facts, mounted bundles and time.
    pub fn debug_lines(&self) -> Vec<String> {
        let mut out = vec![format!(
            "beat {} ({:.2}s / {:.2}s)",
            self.current,
            self.time_in_beat.as_secs_f32(),
            self.elapsed.as_secs_f32()
        )];
        for (k, v) in self.facts.iter() {
            out.push(format!("  fact {k} = {v:?}"));
        }
        for m in self.mounted() {
            out.push(format!("  mounted {m}"));
        }
        out
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cell::Style;
    use crate::node::Node;
    use crate::scene::SceneEntity;

    fn ms(n: u64) -> Duration {
        Duration::from_millis(n)
    }

    fn text(label: &str) -> Node {
        Node::text(label, Style::default()).width(4.0).height(1.0)
    }

    /// A branch/join story mirroring the tactical-choice shape.
    fn tactical_story() -> Story {
        Story::new("tactical")
            .beat(
                Beat::new("tactical")
                    .min_duration(ms(50))
                    .transition(Condition::user("pool"), "pool")
                    .transition(Condition::user("crew"), "crew")
                    .after(ms(500), "download"),
            )
            .beat(
                Beat::new("pool")
                    .on_enter(StoryAction::set_bool("pool-distraction", true))
                    .after(ms(100), "download"),
            )
            .beat(
                Beat::new("crew")
                    .on_enter(StoryAction::set_bool("crew-reinforced", true))
                    .after(ms(100), "download"),
            )
            .beat(Beat::new("download").terminal())
    }

    #[test]
    fn default_timeout_path_reaches_download() {
        let story = tactical_story();
        let mut d = story.start();
        for _ in 0..60 {
            d.update(ms(10), &[]);
        }
        assert_eq!(d.current_beat(), "download");
        assert!(!d.facts().bool("pool-distraction"));
        assert!(!d.facts().bool("crew-reinforced"));
    }

    #[test]
    fn user_choice_after_min_duration_selects_the_arrow() {
        let story = tactical_story();
        let mut d = story.start();
        d.update(ms(10), &[]);
        // Too early: ignored by min_duration.
        d.update(ms(10), &[StoryEvent::user_selected("pool")]);
        assert_eq!(d.current_beat(), "tactical");
        // Past min duration: selects the Pool arrow.
        d.update(ms(50), &[StoryEvent::user_selected("pool")]);
        assert_eq!(d.current_beat(), "pool");
        assert!(d.facts().bool("pool-distraction"));
    }

    #[test]
    fn branches_differ_locally_but_reconverge() {
        let story = tactical_story();

        let mut pool = story.start();
        pool.update(ms(60), &[StoryEvent::user_selected("pool")]);
        let mut crew = story.start();
        crew.update(ms(60), &[StoryEvent::user_selected("crew")]);

        // Local facts differ.
        assert!(pool.facts().bool("pool-distraction"));
        assert!(!pool.facts().bool("crew-reinforced"));
        assert!(crew.facts().bool("crew-reinforced"));
        assert!(!crew.facts().bool("pool-distraction"));

        // Both reconverge at Download.
        for _ in 0..20 {
            pool.update(ms(10), &[]);
            crew.update(ms(10), &[]);
        }
        assert_eq!(pool.current_beat(), "download");
        assert_eq!(crew.current_beat(), "download");
    }

    #[test]
    fn mounted_bundles_run_on_time_since_mount() {
        let story = Story::new("a")
            .bundle(EffectBundle::new("plague").effect(Effect::set_custom(
                crate::scene::SceneTarget::Id(crate::scene::SceneId(0)),
                7,
                1.0,
            )))
            .beat(
                Beat::new("a")
                    .on_enter(StoryAction::mount("plague"))
                    .after(ms(100), "b"),
            )
            .beat(
                Beat::new("b")
                    .on_enter(StoryAction::unmount("plague"))
                    .terminal(),
            );
        let mut d = story.start();
        assert!(d.mounted().any(|m| m == "plague"));
        d.update(ms(50), &[]);
        assert_eq!(d.current_beat(), "a");
        d.update(ms(60), &[]);
        assert_eq!(d.current_beat(), "b");
        assert!(!d.mounted().any(|m| m == "plague"));
    }

    #[test]
    fn story_replay_is_deterministic_and_identical() {
        let story = tactical_story();
        let mut d = story.start();
        d.update(ms(60), &[StoryEvent::user_selected("crew")]);
        for _ in 0..20 {
            d.update(ms(10), &[]);
        }
        let original = d.trace().beat_sequence().join(">");

        let replayed = story.replay(d.trace(), ms(10));
        let replay_seq = replayed.trace().beat_sequence().join(">");
        assert_eq!(original, replay_seq);
        assert_eq!(replayed.current_beat(), d.current_beat());
    }

    #[test]
    fn facts_are_semantic_and_persistent() {
        let story = Story::new("a")
            .beat(
                Beat::new("a")
                    .on_enter(StoryAction::set_bool("plague-active", true))
                    .after(ms(10), "b"),
            )
            .beat(Beat::new("b").after(ms(10), "c"))
            .beat(Beat::new("c").terminal());
        let mut d = story.start();
        d.update(ms(15), &[]);
        assert_eq!(d.current_beat(), "b");
        assert!(
            d.facts().bool("plague-active"),
            "fact persists across beats"
        );
        d.update(ms(15), &[]);
        assert_eq!(d.current_beat(), "c");
        assert!(d.facts().bool("plague-active"), "fact still persists");
    }

    #[test]
    fn presentation_composes_beat_and_bundle_effects() {
        let mut scene = Scene::new();
        let a = scene.add(SceneEntity::new("a", text("a")));
        let t = crate::scene::SceneTarget::Id(a);
        let story = Story::new("a")
            .bundle(EffectBundle::new("b").effect(Effect::translate(
                t,
                (0.0, 0.0),
                (5.0, 0.0),
                ms(100),
            )))
            .beat(
                Beat::new("a")
                    .on_enter(StoryAction::mount("b"))
                    .effect(Effect::set_custom(t, 1, 2.0))
                    .after(ms(200), "z"),
            )
            .beat(Beat::new("z").terminal());
        let mut d = story.start();
        d.update(ms(50), &[]);
        let p = d.presentation(&scene);
        assert_eq!(p.offset_of(&scene, a), (3, 0)); // 2.5 rounds to 3
        assert_eq!(p.custom(a, 1), Some(2.0)); // beat effect
    }

    #[test]
    fn debug_inspector_reports_beat_facts_and_mounts() {
        let story = Story::new("a")
            .bundle(EffectBundle::new("fx").effect(Effect::identity()))
            .beat(
                Beat::new("a")
                    .label("Arrival")
                    .on_enter(StoryAction::set_bool("seen", true))
                    .on_enter(StoryAction::mount("fx"))
                    .terminal(),
            );
        let d = story.start();
        let lines = d.debug_lines();
        assert!(lines[0].contains("a"));
        assert!(lines.iter().any(|l| l.contains("seen")));
        assert!(lines.iter().any(|l| l.contains("mounted fx")));
        assert_eq!(d.beat_label(), "Arrival");
    }
}
